name: Node Continuous Integration

on: 
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8
      with:
        heroku_api_key: ${{b09052d4-978f-4513-8461-dc49db9d5199}}
        heroku_app_name: "chart_phy_lit_gui" #Must be unique in Heroku
        heroku_email: "devcommunity2020@gmail.com"
      - name: Install Packages
        run: yarn install
      # - name: Run test case
      #   run: yarn test
      - name: Start Server
        run: yarn start


  